### ISSUE TITLE
Convergence failure in calculation of scale factor for integration step size

### ISSUE THREAD

**Issue by mindriot101** [lkreidberg/batman#15]
Hi, when using batman occasionally I get the following error: "Convergence failure in calculation of scale factor for integration step size". I know this occurs if the `fac` computation takes too many iterations, but i'm wondering if you have any intuition as to why this is happening? Is it some combination of the model parameters that's causing this?

If it's related to the parameters I can get hold of the parameters which are causing this issue. Alternatively could I just bump up the 1000 iteration limit and hope?

**Comment by mindriot101** [comment]
I may have just answered my own question - i was simulating planets with a radius of 0R<sub>J</sub> 😳

**Comment by lkreidberg** [comment]
ok great! that would be a problem :)
