### ISSUE TITLE
Batman not calculating the transit at the "correct" time

### ISSUE THREAD

**Issue by betapicc** [lkreidberg/batman#17]
Hello, we have a data set containing flux and time for a timespan of around 80 days. There are however some time gaps in our data where we have no values. Using batman, we tried to simulate transits into our data. If we take the data as if it were taken with a fixed dt between these 80 days, batman seems to be working fine. 
However, when trying it with the time gapped data, it seems to be working incorrectly. Below you can find a screenshot with our data and a plot of the different batman transits. In blue you can see the transits as if the data was with a fixed dt. These have a nice periodicity of 4.5 days. In green you see the transits when using the times from our (red) gapped data. These have a varying periodicity. All plots have the same amount of data points.
Can you see anything we're doing wrong or can you think of a solution to fix this problem?
![screenshot](https://cloud.githubusercontent.com/assets/26432322/23944581/ad2dffe2-0973-11e7-81d5-d7cb679c8b79.png)

**Comment by betapicc** [comment]
Converting the time series from our data into a numpy array seems to have fixed the problem

**Comment by lkreidberg** [comment]
ok great - glad you were able to sort it out!

I'll add a warning about this to the documentation to avoid the problem in the future.
