### ISSUE TITLE
Issues with low resampling on supersampler

### ISSUE THREAD

**Issue by awmann** [lkreidberg/batman#18]
We've noticed using small (2-10) values for resampling creates artifacts (wiggles) in the model light curve. This doesn't appear at high values (>15). See blue resampled model in the light curves below. 

![bad_lc_model](https://cloud.githubusercontent.com/assets/6567968/24302435/a3a45f70-1080-11e7-8773-8efcb86f4d2a.png)

![lc_model_osamp15](https://cloud.githubusercontent.com/assets/6567968/24302441/a7795e5c-1080-11e7-8c27-58fd989b08d1.png)

**Comment by lkreidberg** [comment]
weird, I haven't seen that before! can you give me a code snippet that reproduces the problem?

**Comment by lkreidberg** [comment]
Nm - I figured it out. It's not a bug - the weird wiggles are just an artifact of how supersampling works.

I attached a figure to illustrate. The black line is the true light curve. The blue points are the light curve sampled every 5 time units - with no supersampling. The red points ARE supersampled, with supersample_factor = 2 and exp_time = 10. In other words, each red point should be the average of the blue point on either side of it. And that's exactly what the code outputs.

The way to fix the wiggles is just to use a larger supersample_factor - as you noted.

Anyway, thanks for pointing this out! I've always had short exposure times so this has never been an issue for me.
![lc](https://cloud.githubusercontent.com/assets/1859463/24322668/56bd6a02-113f-11e7-9caf-79a756857f37.png)

**Comment by awmann** [comment]
ah, you beat me to it. 
import batman
import numpy as np
import matplotlib.pyplot as plt


params = batman.TransitParams()
params.t0 = 0.                       #time of inferior conjunction
params.per = 1.                      #orbital period
params.rp = 0.1                      #planet radius (in units of stellar radii)
params.a = 15.                       #semi-major axis (in units of stellar radii)
params.inc = 87.                     #orbital inclination (in degrees)
params.ecc = 0.                      #eccentricity
params.w = 90.                       #longitude of periastron (in degrees)
params.u = [0.1, 0.3]                #limb darkening coefficients
params.limb_dark = "quadratic"       #limb darkening model


t = np.linspace(-0.05, 0.05, 50000)

m1 = batman.TransitModel(params, t)    #initializes model
m2 = batman.TransitModel(params, t, supersample_factor = 5, exp_time = 0.02)
m3 = batman.TransitModel(params, t, supersample_factor = 10, exp_time = 0.02)
m4 = batman.TransitModel(params, t, supersample_factor = 15, exp_time = 0.02)
flux1 = m1.light_curve(params)          
flux2 = m2.light_curve(params)         
flux3 = m3.light_curve(params)      
flux4 = m3.light_curve(params)     

plt.plot(t, flux1)
plt.plot(t, flux2)
plt.plot(t, flux3)
plt.plot(t, flux4)
plt.xlabel("Time from central transit")
plt.ylabel("Relative flux")
plt.show()

<img width="596" alt="screen shot 2017-03-25 at 8 48 04 am" src="https://cloud.githubusercontent.com/assets/6567968/24322717/cdfeac5a-1137-11e7-8449-a30074038235.png">
