### ISSUE TITLE
Space/Tab problem in transitmodel

### ISSUE THREAD

**Issue by hposborn** [lkreidberg/batman#23]
```
  File "/anaconda/envs/py3/lib/python3.6/site-packages/batman/transitmodel.py", line 136
    self.ds = _rsky._rsky(self.t_supersample, params.t0, params.per, params.a, params.inc*pi/180., params.ecc, params.w*pi/180., self.transittype, self.nthreads)
                                                                                                                                                                 ^
TabError: inconsistent use of tabs and spaces in indentation
```
This bug randomly appeared seemingly without changing anything else... (so maybe it's the fault of my bug-filled conda). It seems python stopped liking the spaces (rather than tabs) on line 136 of transitmodel. I fixed by deleting the spaces and putting tabs in manually, but in case anyone else gets this error, maybe you'd better do the same on the master branch. Awesome code btw!

**Comment by lkreidberg** [comment]
Thanks, just fixed this! and corrected another small bug, so now the latest version is 2.4.5.
