### ISSUE TITLE
Error when importing batman

### ISSUE THREAD

**Issue by Giumartos** [lkreidberg/batman#34]
Hello!
I'm trying to run a code which uses a library that has batman as a dependency, but I am receiving the following error message:

File "/home/giumartos/.local/lib/python2.7/site-packages/juliet/fit.py", line 2, in <module>
    import batman
  File "/home/giumartos/.local/lib/python2.7/site-packages/batman/__init__.py", line 6, in <module>
    from .transitmodel import *
  File "/home/giumartos/.local/lib/python2.7/site-packages/batman/transitmodel.py", line 18, in <module>
    from . import _nonlinear_ld
ImportError: /home/giumartos/.local/lib/python2.7/site-packages/batman/_nonlinear_ld.so: undefined symbol: intensity

I have installed batman using pip in other computers also, but I had the same problem. Any guess on what may be happening? Thank you!

**Comment by lkreidberg** [comment]
Hmmmm ... I've never seen this issue before. Have you tried installing batman separately?

What OS are you using?

**Comment by Giumartos** [comment]
Yes, I have tried! I am using Ubuntu 18.04.

**Comment by lkreidberg** [comment]
Weird! try installing from source and running the tests (instructions at https://www.cfa.harvard.edu/~lkreidberg/batman/installation.html)

**Comment by lkreidberg** [comment]
Hi Giulia, just checking about whether you made any progress on this? I heard from another Ubuntu user that they had a similar problem.

I'm not running Ubuntu, so it's hard for me to debug this one.

**Comment by hippke** [comment]
I have a machine with Ubuntu 18.04 and it works nicely.
This looks like a compiler/linker incompatibility with gcc (?) and Python 2.7.
Any chance you @Giumartos can try Python 3? Alternatively (or in addition), use conda? Python 2 is end of life.

**Comment by Giumartos** [comment]
Hi Laura, unfortunatelly I didn't make any progress. I tried installing it from source but I received the following message running the tests:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "batman/__init__.py", line 6, in <module>
    from .transitmodel import *
  File "batman/transitmodel.py", line 18, in <module>
    from . import _nonlinear_ld
ImportError: cannot import name _nonlinear_ld
 
@hippke, I am already using Python 3 :) I tried to install batman using conda, but it looks like the package is not available:

PackagesNotFoundError: The following packages are not available from current channels:

  - batman-package

**Comment by hippke** [comment]
You are, perhaps accidentially, using Python 2 - see your first post in this issue which says
`File "/home/giumartos/.local/lib/python2.7/site-packages/juliet/fit.py", line 2, in
import batman`

**Comment by RockHoward** [comment]
Similar issue but I solved it with the --user option.

pip install --user --upgrade pip

pip install --user batman

**Comment by Giumartos** [comment]
@hippke yes! I think this was the issue. Everything is running as expected now. Thank you very much!!

**Comment by lkreidberg** [comment]
awesome - thanks so much!!
