### ISSUE TITLE
m.fac = None ?    step size factor not available

### ISSUE THREAD

**Issue by 3fon3fonov** [lkreidberg/batman#35]
I don't really have problems with batman, but I was trying to see if I can speed-up a bit the transit light curve calculation with batman while doing an MCMC or optimization runs wit the Exo-Striker,. According to:

https://www.cfa.harvard.edu/~lkreidberg/batman/trouble.html#help-batman-is-running-really-slowly-why-is-this

you said that I can use the "fac" keyword in order to fix the step size factor.

Well, I am trying to, but it is not working. Perhaps the print screen below shows best what is going on:

![TheExoStriker_with_batman](https://user-images.githubusercontent.com/44244057/81820689-3a2a2c80-9531-11ea-9cdb-8f10f7f59646.png)

To explain, batman is working as you can see from the plot. On the right side is the Jupyter test bentch where I try to get the step size factor from a constructed model with the same params as those in the GUI frame, but it returns 'None'. The same happens behind the GUI.  

Perhaps I am missing something?

Cheers,
Trifon

**Comment by lkreidberg** [comment]
Hmm ... one question to start: which limb darkening model are you using? For linear and quadratic models, the transit light curve is calculated analytically (rather than by integration over the stellar disk), so the fac parameter isn't used. That might be why it's not defined.

**Comment by 3fon3fonov** [comment]
Well, that explains everything. Sorry if this was obvious and I didn't realize it.
For this particular run, I was using Quadratic LD. 
I can confirm that using "nonlinear", then the step size factor is available! 

I am closing since this was never an issue.
