### ISSUE TITLE
Incorrect transit model when times are non-contiguous

### ISSUE THREAD

**Issue by danhey** [lkreidberg/batman#37]
Hi Laura, thanks for the awesome package! I've stumbled upon this really strange bug when trying to compute a transit for a given set of times which are read from a local file.

Reading the times in using numpy and calculating a transit model on them gives a really unusual looking transit. I've found this is because the times are non-contiguous in memory, here's a plot of a transit using non-contiguous times:
<img width="449" alt="Screen Shot 2020-06-05 at 4 32 02 pm" src="https://user-images.githubusercontent.com/38233719/83844348-29dd2a00-a74a-11ea-86b1-3072dae17ce0.png">

I've uploaded a gist which reproduces the bug: https://gist.github.com/danhey/a5cac73ca554a9a411c56cb60352aab1#file-contiguous-ipynb

If you'd like, I can open a PR which checks that the array is C-contiguous before running the transit model. 

Cheers!

**Comment by lkreidberg** [comment]
Ooooh I have an idea why that might be happening - I'm accessing arrays in kind of a hacky way (see comment below). Maybe that's the source of the probem? A PR with a check for contiguous times would be great!

`/*
    NOTE:  the safest way to access numpy arrays is to use the PyArray_GETITEM and PyArray_SETITEM functions.
    Here we use a trick for faster access and more convenient access, where we set a pointer to the
    beginning of the array with the PyArray_DATA (e.g., f_array) and access elements with e.g., f_array[i].
    Success of this operation depends on the numpy array storing data in blocks equal in size to a C double.
    If you run into trouble along these lines, I recommend changing the array access to something like:
        d = PyFloat_AsDouble(PyArray_GETITEM(ds, PyArray_GetPtr(ds, &i)));
    where ds is a numpy array object.
    Laura Kreidberg 07/2015
    */`
