### ISSUE TITLE
error in install batman

### ISSUE THREAD

**Issue by MohammadEftekhar** [lkreidberg/batman#43]
when I pip install batman-package
terminal shows this error:

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Collecting batman-package
  Using cached batman-package-2.4.6.tar.gz (29 kB)
Requirement already satisfied: numpy in ./snap/jupyter/common/lib/python3.7/site-packages (from batman-package) (1.19.2)
Building wheels for collected packages: batman-package
  Building wheel for batman-package (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /snap/jupyter/6/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cuaealba/batman-package/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cuaealba/batman-package/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-anz3zr3j
       cwd: /tmp/pip-install-cuaealba/batman-package/
  Complete output (22 lines):
  Checking for OpenMP support...
  Did not detect OpenMP support.
  /snap/jupyter/6/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'extras_requires'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/batman
  copying batman/transitmodel.py -> build/lib.linux-x86_64-3.7/batman
  copying batman/openmp.py -> build/lib.linux-x86_64-3.7/batman
  copying batman/plots.py -> build/lib.linux-x86_64-3.7/batman
  copying batman/tests.py -> build/lib.linux-x86_64-3.7/batman
  copying batman/__init__.py -> build/lib.linux-x86_64-3.7/batman
  running build_ext
  building 'batman._nonlinear_ld' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/c_src
  gcc -pthread -B /home/filipe/miniconda3/envs/JUPYTER/compiler_compat -Wl,--sysroot=/ -Wsign-compare-DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/mohammad/snap/jupyter/common/lib/python3.7/site-packages/numpy/core/include -I/snap/jupyter/6/include/python3.7m -c c_src/_nonlinear_ld.c -o build/temp.linux-x86_64-3.7/c_src/_nonlinear_ld.o -std=c99
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for batman-package
  Running setup.py clean for batman-package
Failed to build batman-package
Installing collected packages: batman-package
    Running setup.py install for batman-package ... error
    ERROR: Command errored out with exit status 1:
     command: /snap/jupyter/6/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cuaealba/batman-package/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cuaealba/batman-package/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bejpgonj/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/mohammad/snap/jupyter/common/include/python3.7m/batman-package
         cwd: /tmp/pip-install-cuaealba/batman-package/
    Complete output (22 lines):
    Checking for OpenMP support...
    Did not detect OpenMP support.
    /snap/jupyter/6/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'extras_requires'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/batman
    copying batman/transitmodel.py -> build/lib.linux-x86_64-3.7/batman
    copying batman/openmp.py -> build/lib.linux-x86_64-3.7/batman
    copying batman/plots.py -> build/lib.linux-x86_64-3.7/batman
    copying batman/tests.py -> build/lib.linux-x86_64-3.7/batman
    copying batman/__init__.py -> build/lib.linux-x86_64-3.7/batman
    running build_ext
    building 'batman._nonlinear_ld' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/c_src
    gcc -pthread -B /home/filipe/miniconda3/envs/JUPYTER/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/mohammad/snap/jupyter/common/lib/python3.7/site-packages/numpy/core/include -I/snap/jupyter/6/include/python3.7m -c c_src/_nonlinear_ld.c-o build/temp.linux-x86_64-3.7/c_src/_nonlinear_ld.o -std=c99
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /snap/jupyter/6/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cuaealba/batman-package/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cuaealba/batman-package/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bejpgonj/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/mohammad/snap/jupyter/common/include/python3.7m/batman-package Check the logs for full command output.

m-pip and install wheel doesnt work for I
Thank You

**Comment by lkreidberg** [comment]
Hi, not sure what's causing this, but I have two recommendations:

- Please try a fresh install with the newest version of batman (2.4.7) just uploaded to PyPI.
- take a look at the advice in issue 42: https://github.com/lkreidberg/batman/issues/42

Hopefully one of those fixes it!

**Comment by cmcgrud1** [comment]
Think this might also be related to what bhilbert4 was saying https://github.com/lkreidberg/batman/issues/48#issuecomment-844220105

**Comment by lkreidberg** [comment]
closed via issue #48
