### ISSUE TITLE
ImportError when running the tests

### ISSUE THREAD

**Issue by jpathorne** [lkreidberg/batman#55]
I have managed to install batman with no apparent problems but when I run the  'python -c 'import batman; batman.test()' it returns 

![image](https://user-images.githubusercontent.com/91275574/203838525-66f699fd-6590-4d26-8748-9f583c576c5d.png)

Thanks for the help!

**Comment by lkreidberg** [comment]
Hmm I haven't heard of this before - what OS are you using?

**Comment by jpathorne** [comment]
I'm using macOS Monterey version 12.2.1

**Comment by jpathorne** [comment]
I realised I was running the test inside Batman's root directory which was causing the error. Once I run it outside the root directory it was all fine so I will be closing this.
