### ISSUE TITLE
ERROR: Failed building wheel for batman-package

### ISSUE THREAD

**Issue by Panderliran** [lkreidberg/batman#58]
while I use `pip install batman-package` in cmd, I get an error

`Collecting batman-package
  Using cached batman-package-2.4.9.tar.gz (394 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in d:\anaconda3\envs\python39\lib\site-packages (from batman-package) (1.25.0)
Building wheels for collected packages: batman-package
  Building wheel for batman-package (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for batman-package (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      C:\Users\whlih\AppData\Local\Temp\pip-build-env-6eek7j3y\overlay\Lib\site-packages\setuptools\_distutils\dist.py:265: UserWarning: Unknown distribution option: 'extras_requires'
        warnings.warn(msg)
      Checking for OpenMP support...
      Did not detect OpenMP support.
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for batman-package
Failed to build batman-package
ERROR: Could not build wheels for batman-package, which is required to install pyproject.toml-based projects`

how can I solve it?

**Comment by Panderliran** [comment]
I have solved it by downloading Microsoft Visual BuildTools 2022, just like the error shows "Microsoft Visual C++ 14.0 or greater is required". I neglected the messages given by my computer!

**Comment by kazama-kasana** [comment]
i downloaded Visual studio and build tools too but still facing this issue, i have been facing this issue while installing the radvel module for radial velocity analysis too
pls help!
:
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools>pip install batman-package
Collecting batman-package
  Using cached batman-package-2.4.9.tar.gz (394 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from batman-package) (1.26.4)
Building wheels for collected packages: batman-package
  Building wheel for batman-package (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for batman-package (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      C:\Users\DELL\AppData\Local\Temp\pip-build-env-9q_k_b7j\overlay\Lib\site-packages\setuptools\_distutils\dist.py:266: UserWarning: Unknown distribution option: 'extras_requires'
        warnings.warn(msg)
      Checking for OpenMP support...
      Did not detect OpenMP support.
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for batman-package
Failed to build batman-package
ERROR: Could not build wheels for batman-package, which is required to install pyproject.toml-based projects
