### ISSUE TITLE
supersample_factor and exp_time

### ISSUE THREAD

**Issue by NicholasBermuda** [lkreidberg/batman#6]
Hi Laura,

I noticed that when the user sets an exposure time in `TransitModel`, since the supersample factor defaults to 1, there's nothing that makes it clear that both `exp_time` and `supersample_factor` need to be set in order to produce the light curve you want. I think it might be worthwhile to throw a warning or exception in this case, as it might not be obvious to someone who just skims through the documentation. I'm using commit 972164f.

**Comment by lkreidberg** [comment]
Thanks for the suggestion! The code now throws an exception if supersample_factor > 1 and exp_time <= 0.
